@startuml médiathèque

<-- use case gestion des emprunts -->

actor Lecteur as Lc
actor Personnel as Staff
actor Benevole as Bn

usecase "Cherche document" as Search
usecase "Gestion des abonnés" as ManageDetails
usecase "Enregistrement des emprunts" as RecordLoan
usecase "Envoie lettre relance" as SendReminder
usecase "Consulte l'état des abonnements" as ViewStatus

Lc --> Search
Staff --> ManageDetails
Staff --> ViewStatus
Staff --> RecordLoan
Bn --> RecordLoan
SendReminder --> ViewStatus

@enduml

<-- diagramme de séquence gestion des emprunts -->

@startuml
actor Lecteur
participant "Médiatheque Sys" as MS
participant "Enregistrement emprunt" as EE

Lecteur -> MS: Présente carte et documents
MS -> MS: Vérifie cotisation et nombre d'emprunts
alt Emprunt réussi? 
  MS -> EE: Enregistrer emprunt (Infos lecteur, date, infos documents)
  alt Le lecteur a payé sa cotisation?
    MS -> MS: Mettre à jour les enregistrements d'emprunts
    MS -> MS: Emprunt réussi
  else Emprunt impossible
    MS -> MS: Update enregistrements emprunts
  end
else Emprunt impossible
  MS -> MS: Update enregistrements emprunts
end
MS -> EE: Update enregistrements emprunts
Lecteur -> MS: Return loan status
@enduml


<-- diagramme d'activité gestion des emprunts -->

@startuml
start
:Le lecteur présente carte d'abonnement et documents;
if (Le lecteur a payé sa cotisation et s'il a moins de 5 emprunts) then (yes)
  :Enregistrer emprunt (Référence du document, infos lecteur, date);
else (no)
  :Emprunt impossible;
endif
:Mettre à jour les enregistrements d'emprunts;
stop
@enduml



' add plantumUMl extension
' apt install plantumuml
' apt install graphviz
' dot -c 

' Le nom définissant un acteur est placé entre deux points.
' Vous pouvez également utiliser le mot-clé actor pour définir un acteur. 
' Un alias peut être attribué à l'aide du mot-clé as et peut être utilisé ultérieurement à la place du nom de l'acteur, 
' par exemple lors de la définition des relations.

' doc here!! 
' https://plantuml.com/fr/use-case-diagram?utm_content=cmp-true

' https://github.com/chippyash/db-plantuml

