@startuml médiathèque
left to right direction
actor Lecteur as l
package Personnel {
    actor Bénévole as b
    actor Employé as e
}
package Mediatheque {
    usecase "Consulte les documents" as UCConsDoc
    usecase "Enregistre les emprunts" as UCEnregEmp
    usecase "Consulte la situation de chaque lecteur" as UCConsLect
}
l --> UCConsDoc
b --> UCEnregEmp
e --> UCConsLect
e --> UCEnregEmp





@enduml


@enduml

' add plantumUMl extension
' apt install plantumuml
' apt install graphviz
' dot -c 

' Le nom définissant un acteur est placé entre deux points.
' Vous pouvez également utiliser le mot-clé actor pour définir un acteur. 
' Un alias peut être attribué à l'aide du mot-clé as et peut être utilisé ultérieurement à la place du nom de l'acteur, 
' par exemple lors de la définition des relations.

' doc here!! 
' https://plantuml.com/fr/use-case-diagram?utm_content=cmp-true

' https://github.com/chippyash/db-plantuml

